version: '3.3'

services:
  geradorversiculo:
    container_name: "geradorversiculo-app"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/workspace:cached
    ports:
      - "8080:8080"
    user: root