version: '3.3'

services:
  geradorversiculo:
    container_name: geradorversiculo
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../:/workspace:cached
    ports:
      - "8080:8080"
    user: root